# Generated by Django 4.0.5 on 2022-12-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(max_length=20)),
                ('dpt_description', models.TextField(max_length=355)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=27)),
                ('doc_spec', models.CharField(max_length=20)),
                ('doc_img', models.ImageField(upload_to='doctor')),
                ('dpt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.department')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_phone', models.CharField(max_length=10)),
                ('p_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.doctor')),
                ('dpt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.department')),
            ],
        ),
    ]
